const places = [
  {name:'Shibuya Sky',area:'Shibuya',meta:'Sunset views · ¥2,500',img:'https://images.unsplash.com/photo-1542931287-023b922fa89b?auto=format&fit=crop&w=500&q=85',vote:'must',count:4},
  {name:'Meiji Jingu',area:'Harajuku',meta:'Shrine & gardens · Free',img:'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=500&q=85',vote:'must',count:4},
  {name:'Tsukiji Outer Market',area:'Tsukiji',meta:'Street food · ¥1,800',img:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=500&q=85',vote:'interested',count:3},
  {name:'teamLab Planets',area:'Toyosu',meta:'Immersive art · ¥3,800',img:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=500&q=85',vote:'must',count:4},
  {name:'Shimokitazawa cafés',area:'Shimokitazawa',meta:'Vintage & coffee · ¥900',img:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=500&q=85',vote:'interested',count:3}
];
const opportunities = [
 {id:'hotel',title:'Tokyo Bay Hotel: Weekend guest-experience study',type:'TRAVEL EXPERIMENT',meta:'May 24–25 · Odaiba',copy:'Stay, explore, and share feedback—get a 20% stay credit.',img:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=85',badge:'MATCHES YOUR TRIP'},
 {id:'school',title:'Nagano Rural School Culture Day',type:'LOCAL EXCHANGE',meta:'Jun 7 · Nagano',copy:'Meet local students and share your culture in a hosted, public program.',img:'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=800&q=85',badge:'VERIFIED HOST'},
 {id:'market',title:'Kyoto Night Market tourism pilot',type:'STUDENT OFFER',meta:'May 30 · Kyoto',copy:'Free entry for travelers who help test a new night-market route.',img:'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=85',badge:'FREE ENTRY'},
 {id:'farm',title:'Kawagoe food walk: route tester day',type:'TRAVEL EXPERIMENT',meta:'May 25 · Kawagoe',copy:'Try local treats and help a small city shape its new walking tour.',img:'https://images.unsplash.com/photo-1526481280695-3c687fd643ed?auto=format&fit=crop&w=800&q=85',badge:'¥1,000 CREDIT'},
 {id:'hostel',title:'First stay at NEST Hostel Shinjuku',type:'STUDENT OFFER',meta:'Any weekend · Shinjuku',copy:'A cozy group room and late check-out for student travelers.',img:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=85',badge:'20% OFF'},
 {id:'farmstay',title:'Nagano farm & food weekend',type:'LOCAL EXCHANGE',meta:'Jun 14–15 · Nagano',copy:'A verified community weekend with farm cooking and public meet-up.',img:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=85',badge:'VERIFIED HOST'}
];
const dayPlans=[
 {day:'Day 1',area:'Shibuya & Harajuku',cost:'¥5,700',stops:[['Morning','Meiji Jingu'],['Afternoon','Shibuya Sky'],['Evening','Uobei + cafés']]},
 {day:'Day 2',area:'Tsukiji & Tokyo Bay',cost:'¥7,400',stops:[['Morning','Tsukiji Outer Market'],['Afternoon','teamLab Planets'],['Evening','Odaiba waterfront']]},
 {day:'Day 3',area:'Old Tokyo & parks',cost:'¥4,200',stops:[['Morning','Senso-ji'],['Afternoon','Ueno Park'],['Evening','Shimokitazawa cafés']]}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function renderPlaces(){ $('#places-list').innerHTML=places.map((p,i)=>`<article class="place-card"><img src="${p.img}" alt="${p.name}"/><div class="place-content"><span class="tag ${p.vote==='must'?'coral':'purple'}">${p.vote==='must'?'MUST VISIT':'GROUP PICK'}</span><h3>${p.name}</h3><div class="place-info"><span>⌖ ${p.area}</span><span>·</span><span>${p.meta}</span></div></div><div class="vote-box"><span><b>${p.count}/4</b> want to go</span><div class="vote-buttons" data-index="${i}"><button data-vote="must" class="${p.vote==='must'?'selected':''}">♥ Must</button><button data-vote="interested" class="${p.vote==='interested'?'selected':''}">◌ Into it</button><button data-vote="skip" class="${p.vote==='skip'?'selected':''}">Skip</button></div></div></article>`).join('');
 $$('.vote-buttons button').forEach(button=>button.onclick=()=>{let index=button.parentElement.dataset.index;places[index].vote=button.dataset.vote;places[index].count=button.dataset.vote==='must'?4:button.dataset.vote==='interested'?3:1;renderPlaces(); toast('Your vote is in — the group can see it');}); }
function renderOpps(target, limit=opportunities.length,large=false){ $(target).innerHTML=opportunities.slice(0,limit).map(o=>`<article class="opp-card ${large?'large':''}"><div class="opp-image" style="background-image:url('${o.img}')"><span class="match-badge">✦ ${o.badge}</span></div><div><span class="tag ${o.type==='LOCAL EXCHANGE'?'purple':o.type==='STUDENT OFFER'?'yellow':'coral'}">${o.type}</span><h3>${o.title}</h3><p>${o.copy}</p><div class="opp-meta">⌖ ${o.meta}</div><button class="under-link detail-btn" data-id="${o.id}">See details →</button></div></article>`).join(''); $$(target+' .detail-btn').forEach(b=>b.onclick=()=>showDetail(b.dataset.id)); }
function renderDays(){ $('#day-list').innerHTML=dayPlans.map((d,i)=>`<div class="day-item"><div class="day-heading"><div><h3>${d.day} <span>${d.area}</span></h3><span>${d.cost} / person</span></div><span>⌄</span></div><div class="stops">${d.stops.map(s=>`<div class="stop"><b>${s[0]}</b> · ${s[1]}</div>`).join('')}</div></div>`).join(''); }
function renderBudget(cheap=false){ const amounts=cheap?[6200,3600,8600,9100]:[10800,4800,9400,7150];const data=[['⌂','Stay','2 nights, split with friends'],['⇄','Transport','Airport + metro'],['♨','Food & drinks','Your saved spots'],['✦','Things to do','Tickets & extras']]; const total=amounts.reduce((a,b)=>a+b,0); $('#cost-breakdown').innerHTML=data.map((d,i)=>`<div class="cost-item"><span class="cost-icon">${d[0]}</span><div><strong>${d[1]}</strong><p>${d[2]}</p></div><strong>¥${amounts[i].toLocaleString()}</strong></div>`).join(''); $('#budget-total').textContent='¥'+total.toLocaleString();$('#budget-left').textContent='¥'+(40000-total).toLocaleString()+' left to play with';$('#budget-fill').style.width=(total/400)+'%'; $('#stay-title').textContent=cheap?'NUI. HOSTEL & BAR LOUNGE':'MUSTARD™ Hotel Shibuya';$('#stay-copy').textContent=cheap?'Friendly dorm-style group room · 2 nights · near Kuramae':'Stylish group room · 2 nights · 12 min from Shibuya';$('#stay-price').textContent=cheap?'¥6,200':'¥10,800';$('#stay-tag').textContent=cheap?'CHEAPER PICK':'YOUR STAY';$('#stay-image').src=cheap?'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=85':'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=85'; $('#tips-title').textContent=cheap?'Nice! Here’s what you gained':'Easy ways to keep it comfortable';const tips=cheap?[['✦','¥7,950 saved','Your plan now leaves room for souvenirs.'],['☕','Local breakfast','Swap hotel breakfast for a ¥600 café stop.'],['↗','One transit pass','Use a 72-hour subway pass for more freedom.']]:[['☼','Try a capsule hotel','Swap the stay and save around ¥4,600.'],['◌','Free shrine morning','Keep Meiji Jingu in—great memories, ¥0.'],['↗','Take the subway','The local route is easy and saves ¥1,200.']];$('#tips-grid').innerHTML=tips.map(t=>`<article class="tip"><span>${t[0]}</span><h3>${t[1]}</h3><p>${t[2]}</p></article>`).join(''); }
function showDetail(id){const o=opportunities.find(x=>x.id===id); const isExchange=o.type==='LOCAL EXCHANGE'; $('#detail-content').innerHTML=`<div class="detail-layout"><div class="detail-content"><span class="tag ${isExchange?'purple':'coral'}">${o.type}</span><h1>${o.title}</h1><span class="verified">✓ ${isExchange?'Verified community organizer':'Verified partner program'}</span><p>${o.copy} This is an opt-in public program designed for small groups and solo travelers alike.</p><div class="detail-info"><div><small>WHEN</small><strong>${o.meta.split(' · ')[0]}</strong></div><div><small>WHERE</small><strong>${o.meta.split(' · ')[1]}</strong></div><div><small>GROUP SIZE</small><strong>2–8 travelers</strong></div><div><small>COST</small><strong>${isExchange?'¥2,500 / person':'Free to join'}</strong></div></div></div><div><img class="detail-image" src="${o.img}" alt="${o.title}"/><div class="safety-card"><p class="eyebrow">HOSTED WITH CARE</p><h3>A friendly, public experience</h3><ul><li>Verified organizer and clear group schedule</li><li>Public meeting point: ${isExchange?'Nagano Station east gate':'Odaiba Seaside Park entrance'}</li><li>Safety guidelines sent before confirmation</li></ul><button class="create-full request-btn" id="request-join">Request to join →</button></div></div></div>`; $('#request-join').onclick=()=>toast('Request sent — we’ll keep it in your trip board'); navigate('opportunity-detail'); }
function navigate(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav-item[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'});}
function toast(text){ const t=$('#toast');t.firstChild.textContent=text+' ';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800);}
function openModal(id){$('#'+id).classList.add('open');}
function closeModals(){$$('.modal-wrap').forEach(m=>m.classList.remove('open'));}
renderPlaces();renderOpps('.home-opps',3);renderOpps('#opportunity-grid',opportunities.length,true);renderDays();renderBudget();
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page))); $('#create-trip').onclick=()=>openModal('create-modal');$('#open-create').onclick=()=>openModal('create-modal');$('.close-modal').onclick=closeModals;$$('.close-modal').forEach(b=>b.onclick=closeModals);$$('.modal-wrap').forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()}); $('#start-trip').onclick=()=>{closeModals();navigate('board');toast('Tokyo trip created — invite your friends!')};$('#paste-link').onclick=()=>openModal('link-modal'); $('#save-link-places').onclick=()=>{closeModals();toast('3 spots from your guide are on the board');};$('#add-place').onclick=()=>toast('Add a place from a link, map, or your saved inspiration');$('#generate-route').onclick=()=>toast('Your 3-day route is ready to share');$$('.pin-btn').forEach(b=>b.onclick=()=>{b.textContent='✓ Pinned to trip';toast(b.dataset.pin+' is now on the board')});let cheap=false;$('#cheap-switch').onclick=()=>{cheap=!cheap;$('#cheap-switch').classList.toggle('on',cheap);renderBudget(cheap);toast(cheap?'Cheaper options applied — saved ¥7,950':'Back to your original picks')};$('#swap-stay').onclick=()=>{if(!cheap){cheap=true;$('#cheap-switch').classList.add('on');renderBudget(true);toast('We found a great hostel swap')}else toast('You’re already seeing the best low-cost stay')};$$('.filter').forEach(f=>f.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');const label=f.textContent.trim();const subset=label==='All matches'?opportunities:opportunities.filter(o=>o.type.toLowerCase().includes(label.replace(' offers',' offer').replace('Local exchange','local exchange').replace('Free & low cost','zzz').toLowerCase())); const target=$('#opportunity-grid');target.innerHTML='';(subset.length?subset:opportunities.filter(o=>o.badge==='FREE ENTRY')).forEach(o=>{const i=opportunities.indexOf(o);target.insertAdjacentHTML('beforeend',`<article class="opp-card large"><div class="opp-image" style="background-image:url('${o.img}')"><span class="match-badge">✦ ${o.badge}</span></div><div><span class="tag coral">${o.type}</span><h3>${o.title}</h3><p>${o.copy}</p><div class="opp-meta">⌖ ${o.meta}</div><button class="under-link detail-btn" data-id="${o.id}">See details →</button></div></article>`)});$$('#opportunity-grid .detail-btn').forEach(b=>b.onclick=()=>showDetail(b.dataset.id));});
